name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        yarn
        npm run build
    - name : Deploy
      run: |
        git add -f static/bundle.js
        git add -f static/bundle.js.map
        git config --global user.name "FIRST_NAME LAST_NAME"
        git config --global user.email "MY_NAME@example.com"
        
        git commit -m "yeet"
        git push -f ${{ github.token }}@github.com:HastingsGreer/webgrid.git master:gh-pages
